### ISSUE TITLE
Style Guide - Prefer ' over "

### ISSUE THREAD

**Issue by dguilak** [VirPong/human-pong#117]
Test Case ID: SG001

Tester: Daniel Guilak

Category: Style Guide

Test Description: Prefer ‘ over “ for strings.

Preconditions: None

Post conditions: None

Steps: 
Navigate to PlayGame/pong.js line numbers:
45
78
82
88
92
118
153
166-168
172
176
191
195
196
200
203
222
231
237-238

Expected Results: Strings should be delineated with ‘.

Actual Results: Strings are delineated with “.

Priority: Low

Notes: FAIL

**Comment by japele** [comment]
Completed.
