### ISSUE TITLE
Style Guide - Authorship Comments

### ISSUE THREAD

**Issue by dguilak** [VirPong/human-pong#118]
Test Case ID: SG002

Tester: Daniel Guilak

Category: Style Guide

Test Description: Authorship comments at top of JavaScript files.

Preconditions: None

Post conditions: None

Steps: 
Navigate to PlayGame/pong.js line 1.

Expected Results: There should be an authorship comment at the top of the script file.

Actual Results: There is not an authorship comment at the top of the script file

Priority: Low

Notes: FAIL

**Comment by japele** [comment]
Completed.
