### ISSUE TITLE
Style Guide - Use ALL CAPS NAMES for CONSTANTS

### ISSUE THREAD

**Issue by dguilak** [VirPong/human-pong#119]
Test Case ID: SG003

Tester: Daniel Guilak

Category: Style Guide

Test Description: Use names in all-caps for constants.

Preconditions: None

Post conditions: None

Steps: 
Navigate to PlayGame/pong.js line 38.

Expected Results: Non-constant variable names should not be in all caps.

Actual Results: A non-constant variable name is in all caps.

Priority: Low

Notes: FAIL

**Comment by japele** [comment]
Completed.
