### ISSUE TITLE
Style Guide - Do not declare functions within blocks

### ISSUE THREAD

**Issue by dguilak** [VirPong/human-pong#120]
Test Case ID: SG004

Tester: Daniel Guilak

Category: Style Guide

Test Description: Do not declare functions within blocks.

Preconditions: None

Post conditions: None

Steps: 
Navigate to PlayGame/pong.js line numbers:
191
196
200
203

Expected Results: Function should not be declared within blocks.

Actual Results: Function is declared within blocks.

Priority: Low

Notes: FAIL

**Comment by krwenholz** [comment]
Eh I'm thinking we may remove this from the style guide. . . . I like those nested blocks. . . .

**Comment by dguilak** [comment]
Yeah I agree, I just wrote the test case because technically it failed. Haha.

**Comment by krwenholz** [comment]
Okay.  I just wanted input.  Thank you for replying!  You are the only one who does.
