### ISSUE TITLE
Style Guide - Meaningful HTML5 Titles

### ISSUE THREAD

**Issue by dguilak** [VirPong/human-pong#122]
Test Case ID: SG006

Tester: Daniel Guilak

Category: Style Guide

Test Description: HTML5 pages should have a meaningful title.

Preconditions: None

Post conditions: None

Steps: 
Navigate to index.html

Expected Results: There should be a meaningful title.

Actual Results: There is no meaningful title.

Priority: Low

Notes: 
FAIL
“PhoneGap” is not a meaningful title for the purposes of the end-user.

**Comment by krwenholz** [comment]
I like the stern wording of this defect.

**Comment by jandersen737** [comment]
Nice catch!!!  I would propose we change the title to "Welcome to Vir-Pong!"  Would that be acceptable to all involved or does anyone else have a more specific suggestion?
