### ISSUE TITLE
Test Case 2.7: Many spectators

### ISSUE THREAD

**Issue by japele** [VirPong/human-pong#131]
2.7 Many Spectators in Server Defect Document
Version:1.0
Description: Spectators connect to watch a game.
Pre-conditions: System and Clients operational on the same network. Game has begun for playing
clients (using PlayerClient or VisualClient). SpectatorClient is used to connect as a spectator.
Post-conditions: Game proceeds for clients and spectators are able to view the game.
Scenario:
1. Spectator selects to watch a game.
2. Spectator registers with server.
3. Repeat steps 1 and 2 several times. (Refreshing the page can do this.)
Expected Results: The game proceeds up to reasonable expectations.
Pass/Fail: Fail
Comments: For each newly connected spectator, or player, the ball visibly gains speed. Head to
line 144 for the if-statement that causes this issue.

**Comment by dguilak** [comment]
Duplicate.
