### ISSUE TITLE
Test Case 5.1: White space

### ISSUE THREAD

**Issue by garrettdieckmann** [VirPong/human-pong#142]
5.1 White space
Version: 1.0
Description:Look for inconsistent white space.
Pre-conditions:Have code
Post-conditions:N/A
Scenario:N/A
Expected Results:N/A
Pass/Fail: Fail
Comments:
1. 9: Why is there so much white space here?
2. 34: Missing whitespace.
3. 66/67: White space needs cleaning up.
4. 70-77: White space needs cleaning up.
5. 70-77 Suggestion: Use a switch with cases instead of multiple IF statements.

**Comment by dguilak** [comment]
As a general rule, it's not good to use switch cases. I had done that originally, but they generally are frowned upon.
