### ISSUE TITLE
Test Case 5.4: Variables and nomenclature 

### ISSUE THREAD

**Issue by garrettdieckmann** [VirPong/human-pong#145]
5.4 Style Guide Defects - Variables & Nomenclature
Version: 1.0
Description: Variables & Nomenclature.
Pass/Fail: Fail
Comments:
1. What variables are global? They should be noted as such.
2. "a" prex required for parameters (54, 60, 90).

**Comment by dguilak** [comment]
All of these are taken care of in the latest commit, but I'll merge it into the code that works pretty soon.
