### ISSUE TITLE
Install Documentation lacking

### ISSUE THREAD

**Issue by msnow** [VirPong/human-pong#182]
Through numerous instances of people asking for help in regards to installing and troubleshooting both the android sdk and phonegap, it can be concluded that the install documentation in the intermediate report for android is lacking.

Instead of linking to various sites, you should instead have thorough and clear steps to installing the sdk and phonegap.

(Though as far as I can tell, most groups suffer from a lack of good install documentation)

**Comment by krwenholz** [comment]
This is interesting.  I doubt that anything we draft could be any better than that provided by the official sites.  Each install can be very platform specific and requires technical knowledge from the developers themselves.  Could you be more specific about how we can improve our documentation?  Any more specific feedback would be appreciated.
