### ISSUE TITLE
WebUI: Int Report: 5.2: Installation: Install NPM

### ISSUE THREAD

**Issue by kbrooks** [VirPong/human-pong#38]
page 26:
typo in paragraph: "Install NPM:"
says "curl http://npmjs.org/install.sh — sh"
should be "curl http://npmjs.org/install.sh | sh"

**Comment by agrause** [comment]
What do you mean? What was there? What line? What page?

**Comment by kbrooks** [comment]
it has a horizontal bar instead of a vertical bar
