### ISSUE TITLE
Andriod: Missing Required Library

### ISSUE THREAD

**Issue by shelbylee-final** [VirPong/human-pong#45]
A compilation error upon importing project code:
Project is missing required library: 'C:/Users/kwenholz/Programming/phonegap-1.1.0.jar'

Possible solutions: include installation documentation on how to point to a phone-gap file on the local machine

**Comment by krwenholz** [comment]
This saddens me.  Consider it done as soon as teams are back together.

**Comment by jandersen737** [comment]
Agreed.  It shall be done!

**Comment by krwenholz** [comment]
Shelby, do you think this is still a bug although it is mentioned in the developer documentation?  The issue arises from our "company" policy on avoiding the upload of binaries.  Maybe a more specific note in the documentation?
