### ISSUE TITLE
WebUI: Graphical error in drop-down menu

### ISSUE THREAD

**Issue by kbrooks** [VirPong/human-pong#61]
Test Case: Drop-down menu testing
1. Navigate to http://cs340.pugetsound.edu/
2. Hover over drop-down menus with the mouse, not clicking on anything.
3. Verify that the drop-down menus appear when the mouse hovers over them.
4. Verify that the site returns to its original visual state when the drop-down menus disappear.

Notes: Fails on 4. Example: hover over "watch," then hover over "events." A vertical line appears on the page where the left side of the drop-down menu for "events" used to be.

the file that describes the drop-down menu is skins/1/header.php

**Comment by indecisivekatie** [comment]
This is actually in skins/1/header.php, for the record.
