### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by ithasnext** [VirPong/human-pong#88]
Some of the links under "Other links of interest" are broken.
"Osmus" directs to http://cs340.pugetsound.edu/human-pong/WebUI/site/http/osmus/client, which throws a 404 Not Found error.
"another demo" directs to an empty directory at "http://cs340.pugetsound.edu/human-pong/WebUI/site/http/NodePong/"

**Comment by indecisivekatie** [comment]
I might be wrong, but I believe the culled version of our code got rid of those links.

**Comment by ithasnext** [comment]
i havent been able to check this but I'll ask Kyle if it did get fixed.
