### ISSUE TITLE
WebUI: Absolute paths instead of relative paths

### ISSUE THREAD

**Issue by kbrooks** [VirPong/human-pong#92]
The following files use absolute file paths instead of relative paths:
- human-pong / WebUI / site / skins / 1 / footer.php
- human-pong / WebUI / site / skins / 1 / header.php

Many links on the website direct to http://cs340-serv/. If we are running on a differently named server, these links fail. 
For the sake of all that is modular, the code should be changed to use relative paths.

**Comment by ghost** [comment]
Involves further research into our directory organization on the server..
