### ISSUE TITLE
Registering new account

### ISSUE THREAD

**Issue by ithasnext** [VirPong/human-pong#93]
After filling out the form and clicking submit the register_form.php page leads to the page register_process.php page which will not open.  

A Server Error: 500 internal error is thrown.  This page does exist only it wont open.

**Comment by indecisivekatie** [comment]
Kyle and I finally figured out the synatx error that was messing up this page. Not sure if he was planning on logging it anew or not (for the record, it's an extraneous semi colon in whatever line defines $myQuery), but just so you know - the page is now fixed enough that you should be able to run whatever other tests you need on it.
