### ISSUE TITLE
Game inconsistently displays graphics

### ISSUE THREAD

**Issue by msnow** [VirPong/human-pong#97]
The phones only display the game screen with the ball and paddles around 20% of the time. Most of the time only a small gray block is displayed along with the up/down buttons as opposed to the black game area with the ball and paddles. The server still registers up/down button presses and such, so it's only the display on the phones that don't work.

I have not yet found a way to consistently force either outcome. It is also phone independent, one phone may display correctly while the other does not, or vice versa or both will or both won't. The Android Emulator for Eclipse runs into the same issues as well.

Steps to reproduce:
1) Start a game
2) if displaying correctly, end game and restart server
3) GOTO 1

**Comment by msnow** [comment]
I found out where the gray square code is. Lines 5-9ish of gameIndex.html draws the gray square.

Still not sure how to consistently cause this defect or where it is arising from.

Edit: Removing lines 5-9 don't fix it, so this probably isn't related to the problem.

**Comment by krwenholz** [comment]
This "was" a server issue.  I can't actually reproduce the bug at all.  Time to close.

**Comment by josefdlange** [comment]
This was probably being caused by a server error or an error in the .js file that prevented it from attaching to the <canvas> element on the HTML page. Nonetheless, it's still closed!
